In [51]:
import numpy as np
import copy

In [52]:
def printMatrix(V):
    n = len(V)
    m = len(V[0])
    for i in range(n):
        for j in range(m):
                     
            print(f'{V[i][j]:15.08f}' ,  end="  ")
            
        print()
    print()

### Input Section

In [53]:
n = 3
A = np.array([
    [2.,-1.,1.],
    [2.,2.,2.],
    [-1.,-1.,2.]
    ])


## Checking for Diagonal Dominance

In [54]:
def dom(A,n):
    for i in range(n):
        sum = 0
        for j in range(n):
            if(i!=j):
                sum+=A[i][j]
        if(A[i][i]<sum):
            return "GIVEN MATRIX IS NOT DIAGONALLY DOMINANT"
    return "GIVEN MATRIX IS DIAGONALLY DOMINANT"

In [55]:
dom(A,n)

'GIVEN MATRIX IS NOT DIAGONALLY DOMINANT'

In [56]:
# Making D, L, U

D = np.zeros((n,n))
L = np.zeros((n,n))
U = np.zeros((n,n))

for i in range(n):
    for j in range(n):
        if i<j:
            U[i][j] = copy.copy(-A[i][j])
        elif i>j:
            L[i][j] = copy.copy(-A[i][j])
        else:
            D[i][j] = copy.copy(A[i][j])

print("D = ")
printMatrix(D)

print("L = ")
printMatrix(L)

print("U = ")
printMatrix(U)

D = 
     2.00000000       0.00000000       0.00000000  
     0.00000000       2.00000000       0.00000000  
     0.00000000       0.00000000       2.00000000  

L = 
     0.00000000       0.00000000       0.00000000  
    -2.00000000       0.00000000       0.00000000  
     1.00000000       1.00000000       0.00000000  

U = 
     0.00000000       1.00000000      -1.00000000  
     0.00000000       0.00000000      -2.00000000  
     0.00000000       0.00000000       0.00000000  



### Convergence of Jacobi Method

In [57]:
# Jacobi G = inv(D)*(L+U)
invD = np.linalg.inv(D)
print("inverse(D) = ")
printMatrix(invD)
print("L + U =")
printMatrix(L+U)
G = np.matmul(invD,(L+U))
print("G = ")
printMatrix(G)
X,V = np.linalg.eig(G)

print("Eigen Values are:")
for i in X:
    print(i)


inverse(D) = 
     0.50000000       0.00000000       0.00000000  
     0.00000000       0.50000000       0.00000000  
     0.00000000       0.00000000       0.50000000  

L + U =
     0.00000000       1.00000000      -1.00000000  
    -2.00000000       0.00000000      -2.00000000  
     1.00000000       1.00000000       0.00000000  

G = 
     0.00000000       0.50000000      -0.50000000  
    -1.00000000       0.00000000      -1.00000000  
     0.50000000       0.50000000       0.00000000  

Eigen Values are:
(5.551115123125783e-17+1.1180339887498956j)
(5.551115123125783e-17-1.1180339887498956j)
(2.6009723803125757e-17+0j)


### Convergence of Gauss-Siedel Method

In [58]:
# Gauss-Siedel  G = (inv(D-L))*U
DL = D-L
invDL = np.linalg.inv(DL)
printMatrix(invDL)
G = np.matmul(invDL,U)
printMatrix(G)
X,V = np.linalg.eig(G)

print("Eigen Values are:")
for i in X:
    print(i)

     0.50000000       0.00000000       0.00000000  
    -0.50000000       0.50000000       0.00000000  
     0.00000000       0.25000000       0.50000000  

     0.00000000       0.50000000      -0.50000000  
     0.00000000      -0.50000000      -0.50000000  
     0.00000000       0.00000000      -0.50000000  

Eigen Values are:
0.0
-0.5
-0.5
