# SVD Implementation
## Importing libraries

In [115]:
import numpy as np
import copy

## SVD function Definition

In [116]:
def printMatrix(V):
    m = len(V)
    n = len(V[0])
    
    for i in range(m):
        for j in range(n):
            print(f'{V[i][j]:10.05f}' ,  end="  ")
        print()
    print()


def SVD(A):
    m = len(A)
    n = len(A[0])

    At = A.transpose()
    
    AtA = np.matmul(At,A)
    
    AAt = np.matmul(A,At)
    
    # Finding Eigen Values and Vectors of AAt and AtA
    eigValuesAAt, eigVectorsAAt = np.linalg.eig(AAt)
    eigValuesAtA, eigVectorsAtA = np.linalg.eig(AtA)


    # Sorting eigen values in descending order and also changing position of corresponding eigen vectors
    idx = eigValuesAAt.argsort()[::-1]   
    eigValuesAAt = eigValuesAAt[idx]
    eigVectorsAAt = eigVectorsAAt[:,idx]
    eigVectorsAtA = eigVectorsAtA[:,idx]

    # Forming U, D and VT
    U = eigVectorsAAt
    D = eigValuesAAt**0.5
    D = np.diag(D)

    Vt = eigVectorsAtA.transpose()
    
    return U,D,Vt
    

In [117]:
A = np.array(((
    (1,2,3),
    (4,0,6),
    (7,8,9)
)))


U,D,Vt = SVD(A)

In [118]:
print("U = ")
printMatrix(U)
print("D = ")
printMatrix(D)
print("VT = ")
printMatrix(Vt)
printMatrix(U@D@Vt)
printMatrix(A)

U = 
   0.23066     0.05358     0.97156  
   0.40368    -0.91377    -0.04544  
   0.88535     0.40268    -0.23240  

D = 
  15.63377     0.00000     0.00000  
   0.00000     3.81768     0.00000  
   0.00000     0.00000     1.00528  

VT = 
   0.51445     0.48255     0.70886  
   0.20504    -0.87188     0.44472  
   0.83265    -0.08344    -0.54748  

   2.71036     1.48030     2.11250  
   2.49336     6.09074     2.94720  
   7.24135     5.35832    10.62315  

   1.00000     2.00000     3.00000  
   4.00000     0.00000     6.00000  
   7.00000     8.00000     9.00000  



In [119]:
u,d,vt = np.linalg.svd(A)
print("U = ")
printMatrix(u)
print("D = ")
print(d)
print("\nVT = ")
printMatrix(vt)
A_t = u @ d @ vt
printMatrix(A)

U = 
  -0.23066    -0.05358     0.97156  
  -0.40368     0.91377    -0.04544  
  -0.88535    -0.40268    -0.23240  

D = 
[15.63376871  3.81768041  1.00528221]

VT = 
  -0.51445    -0.48255    -0.70886  
   0.20504    -0.87188     0.44472  
  -0.83265     0.08344     0.54748  

   1.00000     2.00000     3.00000  
   4.00000     0.00000     6.00000  
   7.00000     8.00000     9.00000  

