# SVD Implementation
## Importing libraries

In [6]:
import numpy as np
import copy

## SVD function Definition

In [7]:
def printMatrix(V):
    m = len(V)
    n = len(V[0])
    
    for i in range(m):
        for j in range(n):
            print(f'{V[i][j]:10.05f}' ,  end="  ")
        print()
    print()


def SVD(A):
    m = len(A)
    n = len(A[0])

    At = A.transpose()
    
    AtA = np.matmul(At,A)
    
    AAt = np.matmul(A,At)
    
    # Finding Eigen Values and Vectors of AAt and AtA
    eigValuesAAt, eigVectorsAAt = np.linalg.eig(AAt)

    eigValuesAtA, eigVectorsAtA = np.linalg.eig(AtA)

    # Forming U, D and VT
    U = eigVectorsAAt
    
    # Sorting eigen values in descending order
    for i in range(len(eigValuesAAt)-2,0,-1):
        for j in range(len(eigValuesAAt)-1,i,-1):
            if(eigValuesAAt[i]<eigValuesAAt[j]):
                temp = copy.copy(eigValuesAAt[i])
                eigValuesAAt[i] = copy.copy(eigValuesAAt[j])
                eigValuesAAt[j] = copy.copy(temp)


    D = np.zeros((m,n))
    for i in range(m):
        for j in range(n):
            if i==j:
                D[i][j] = (eigValuesAAt[i])**(1/2)
            else:
                D[i][j] = 0

    Vt = eigVectorsAtA.transpose()
    
    return U,D,Vt
    

In [8]:
A = np.array(((
    (1,2,3),
    (4,5,6),
    (7,8,9)
)))

# A = np.array(((
#     (1, -1, 4),
#     (1, 4, -2),
#     (1, 4, 2),
#     (1, -1, 0)
# )))

U,D,Vt = SVD(A)

In [9]:
print("U = ")
printMatrix(U)
print("D = ")
printMatrix(D)
print("VT = ")
printMatrix(Vt)

U = 
  -0.21484    -0.88723     0.40825  
  -0.52059    -0.24964    -0.81650  
  -0.82634     0.38794     0.40825  

D = 
  16.84810     0.00000     0.00000  
   0.00000     1.06837     0.00000  
   0.00000     0.00000     0.00000  

VT = 
  -0.47967    -0.57237    -0.66506  
  -0.77669    -0.07569     0.62532  
   0.40825    -0.81650     0.40825  



In [10]:
u,d,vt = np.linalg.svd(A)
print("U = ")
printMatrix(u)
print("D = ")
print(d)
print("\nVT = ")
printMatrix(vt)

U = 
  -0.21484     0.88723     0.40825  
  -0.52059     0.24964    -0.81650  
  -0.82634    -0.38794     0.40825  

D = 
[1.68481034e+01 1.06836951e+00 4.41842475e-16]

VT = 
  -0.47967    -0.57237    -0.66506  
  -0.77669    -0.07569     0.62532  
  -0.40825     0.81650    -0.40825  

