# Convergence of Gauss-Siedel Method

In [1]:
import numpy as np
import copy

In [2]:
def printMatrix(V):
    n = len(V)
    m = len(V[0])
    for i in range(n):
        for j in range(m):
                     
            print(f'{V[i][j]:15.08f}' ,  end="  ")
            
        print()
    print()

In [3]:
# Diagonal Dominant is only a sufficient condition for convergence. it's not a necessary condition.

def dom(A,n):
    for i in range(n):
        sum = 0
        for j in range(n):
            if(i!=j):
                sum+=A[i][j]
        if(A[i][i]<sum):
            return "GIVEN MATRIX IS NOT DIAGONALLY DOMINANT"
    return "GIVEN MATRIX IS DIAGONALLY DOMINANT"

## Input Section

In [4]:
n = 3
A = np.array([[3.0,-2.,1.],[1.,-6.,8.],[2.,3.,-6.]])
b = np.array([[3],[2],[1]])

## Checking for Diagonal Dominance

In [5]:
dom(A,n)

'GIVEN MATRIX IS NOT DIAGONALLY DOMINANT'

## Making D, L, U

In [6]:
D = np.zeros((n,n))
L = np.zeros((n,n))
U = np.zeros((n,n))

for i in range(n):
    for j in range(n):
        if i<j:
            U[i][j] = copy.copy(-A[i][j])
        elif i>j:
            L[i][j] = copy.copy(-A[i][j])
        else:
            D[i][j] = copy.copy(A[i][j])

print("D = ")
printMatrix(D)

print("L = ")
printMatrix(L)

print("U = ")
printMatrix(U)

D = 
     3.00000000       0.00000000       0.00000000  
     0.00000000      -6.00000000       0.00000000  
     0.00000000       0.00000000      -6.00000000  

L = 
     0.00000000       0.00000000       0.00000000  
    -1.00000000       0.00000000       0.00000000  
    -2.00000000      -3.00000000       0.00000000  

U = 
     0.00000000       2.00000000      -1.00000000  
     0.00000000       0.00000000      -8.00000000  
     0.00000000       0.00000000       0.00000000  



## Calculatig G and c Matrices

In [7]:
# Gauss-Siedel  G = (inv(D-L))*U      c = (inv(D-L))*b

DL = D-L
invDL = np.linalg.inv(DL)
print("inverse(D-L) = ")
printMatrix(invDL)

G = np.matmul(invDL,U)
print("G = ")
printMatrix(G)

c = np.matmul(invDL,b)
print("c = ")
printMatrix(c)

inverse(D-L) = 
     0.33333333       0.00000000       0.00000000  
     0.05555556      -0.16666667      -0.00000000  
     0.13888889      -0.08333333      -0.16666667  

G = 
     0.00000000       0.66666667      -0.33333333  
     0.00000000       0.11111111       1.27777778  
     0.00000000       0.27777778       0.52777778  

c = 
     1.00000000  
    -0.16666667  
     0.08333333  



In [8]:
lambdas, X = np.linalg.eig(G)

print("Eigen Values are:")
for i in lambdas:
    print(i)

Eigen Values are:
0.0
-0.3116982093056535
0.9505870981945423


In [9]:
sp_rad = -1
for i in lambdas:
    if sp_rad<abs(i):
        sp_rad = abs(i)

if(sp_rad<1):
    print(f'\nSpectral Radius of Matrix G is {sp_rad} and its less than 1.')
    print(f'Therefore method Converges.')
else:
    print(f'\nSpectral Radius of Matrix G is {sp_rad} and its greater than 1')


Spectral Radius of Matrix G is 0.9505870981945423 and its less than 1.
Therefore method Converges.
