# Convergence of Jacobi, Guass Siedel and SOR Method

In [1]:
import numpy as np
import copy

In [2]:
def printMatrix(V):
    n = len(V)
    m = len(V[0])
    for i in range(n):
        for j in range(m):
                     
            print(f'{V[i][j]:15.08f}' ,  end="  ")
            
        print()
    print()

## Function for Checking Diagonal Dominance

In [3]:
# Diagonal Dominant is only a sufficient condition for convergence. it's not a necessary condition.

def dom(A,n):
    for i in range(n):
        sum = 0
        for j in range(n):
            if(i!=j):
                sum+=A[i][j]
        if(A[i][i]<sum):
            return "GIVEN MATRIX IS NOT DIAGONALLY DOMINANT"
    return "GIVEN MATRIX IS DIAGONALLY DOMINANT"

## Input Section

In [4]:
# n = 3

# A = np.array([[3.0,-2.,1.],[1.,-6.,8.],[2.,3.,-6.]])
# b = np.array([[3],[2],[1]])
n=2
A = np.array([[3.,9.],[9.,1.]])
b = np.array([[24],[30]])

## Checking for Diagonal Dominance

In [5]:
dom(A,n)

'GIVEN MATRIX IS NOT DIAGONALLY DOMINANT'

## Making D, L, U

In [6]:
D = np.zeros((n,n))
L = np.zeros((n,n))
U = np.zeros((n,n))

for i in range(n):
    for j in range(n):
        if i<j:
            U[i][j] = copy.copy(-A[i][j])
        elif i>j:
            L[i][j] = copy.copy(-A[i][j])
        else:
            D[i][j] = copy.copy(A[i][j])

print("D = ")
printMatrix(D)

print("L = ")
printMatrix(L)

print("U = ")
printMatrix(U)

D = 
     3.00000000       0.00000000  
     0.00000000       1.00000000  

L = 
     0.00000000       0.00000000  
    -9.00000000       0.00000000  

U = 
     0.00000000      -9.00000000  
     0.00000000       0.00000000  



# Convergence of Jacobi Method
## Calculating matrix G and c


In [7]:
# Jacobi G = inv(D)*(L+U)       c = inv(D)*b
invD = np.linalg.inv(D)
print("inverse(D) = ")
printMatrix(invD)

print("L + U =")
printMatrix(L+U)

Gj = np.matmul(invD,(L+U))
print("G = ")
printMatrix(Gj)

cj = np.matmul(invD,b)
print("c = ")
printMatrix(cj)

inverse(D) = 
     0.33333333       0.00000000  
     0.00000000       1.00000000  

L + U =
     0.00000000      -9.00000000  
    -9.00000000       0.00000000  

G = 
     0.00000000      -3.00000000  
    -9.00000000       0.00000000  

c = 
     8.00000000  
    30.00000000  



## Calculating Eigen Values

In [8]:
lambdas,X = np.linalg.eig(Gj)

print("Eigen Values are:")
for i in lambdas:
    print(i)


Eigen Values are:
5.196152422706631
-5.196152422706633


## Calculating Spectral Radius

In [9]:
sp_rad_j = -1
for i in lambdas:
    if sp_rad_j<abs(i):
        sp_rad_j = abs(i)

if(sp_rad_j<1):
    print(f'\nSpectral Radius of Matrix G is {sp_rad_j} and its less than 1.')
    print(f'Therefore method Converges.')
else:
    print(f'\nSpectral Radius of Matrix G is {sp_rad_j} and its greater than 1')
    print(f'Therefore does not method converge.')



Spectral Radius of Matrix G is 5.196152422706633 and its greater than 1
Therefore does not method converge.


# Convergence of Gauss-Siedel Method
## Calculating matrix G and c

In [10]:
# Gauss-Siedel  G = (inv(D-L))*U      c = (inv(D-L))*b

DL = D-L
invDL = np.linalg.inv(DL)
print("inverse(D-L) = ")
printMatrix(invDL)

Gg = np.matmul(invDL,U)
print("G = ")
printMatrix(Gg)

cg = np.matmul(invDL,b)
print("c = ")
printMatrix(cg)

inverse(D-L) = 
     0.33333333       0.00000000  
    -3.00000000       1.00000000  

G = 
     0.00000000      -3.00000000  
     0.00000000      27.00000000  

c = 
     8.00000000  
   -42.00000000  



## Calculating Eigen Values

In [11]:
lambdas, X = np.linalg.eig(Gg)

print("Eigen Values are:")
for i in lambdas:
    print(i)

Eigen Values are:
0.0
27.0


## Calculating Spectral Radius

In [12]:
sp_rad_g = -1
for i in lambdas:
    if sp_rad_g<abs(i):
        sp_rad_g = abs(i)

if(sp_rad_g<1):
    print(f'\nSpectral Radius of Matrix G is {sp_rad_g} and its less than 1.')
    print(f'Therefore method Converges.')
else:
    print(f'\nSpectral Radius of Matrix G is {sp_rad} and its greater than 1')
    print(f'Therefore does not method converge.')


NameError: name 'sp_rad' is not defined

# Convergence of SOR
## Finding w optimum

In [13]:
w = 2 / (1 + (1 - (sp_rad_j**2))**(1/2))

print(f"optimum w = {w}")

optimum w = 1.2404082057734578


## Calculating matrix G and c

In [14]:
# G = ((D − ωL)^−1) *((1 − ω)D + ωU) and c̄ = (ω(D − ωL)^−1) *b

#  w = 0.9 

D_wL = D-(w*L)
invD_wL = np.linalg.inv(D_wL)
print("inverse(D-w*L) = ")
printMatrix(invD_wL)

wD = (1-w)*D
wU = w*U

Gw = np.matmul(invD_wL,(wD + wU))
print("G = ")
printMatrix(Gw)

cw = w*np.matmul(invD_wL,b)
print("c = ")
printMatrix(cw)

inverse(D-w*L) = 
     0.25000000       0.00000000       0.00000000  
    -0.23257654       0.25000000       0.00000000  
    -0.07212246       0.07752551       0.25000000  

G = 
    -0.24040821      -0.93030615       0.00000000  
     0.22365323       0.62506134       0.31010205  
     0.06935533       0.19383280      -0.14424492  

c = 
     7.44244923  
     2.37930522  
    -6.70462181  



## Calculating Eigen Values

In [15]:
lambdas, X = np.linalg.eig(Gw)

print("Eigen Values are:")
for i in lambdas:
    print(i)

Eigen Values are:
(0.24040820577345745+1.3486135817890344e-08j)
(0.24040820577345745-1.3486135817890344e-08j)
(-0.24040820577345776+0j)


## Calculating Spectral Radius

In [16]:
sp_rad_w = -1
for i in lambdas:
    if sp_rad_w<abs(i):
        sp_rad_w = abs(i)

if(sp_rad_w<1):
    print(f'\nSpectral Radius of Matrix G is {sp_rad_w} and its less than 1.')
    print(f'Therefore method Converges.')
else:
    print(f'\nSpectral Radius of Matrix G is {sp_rad_w} and its greater than 1')
    print(f'Therefore does not method converge.')



Spectral Radius of Matrix G is 0.24040820577345784 and its less than 1.
Therefore method Converges.
